name: docs
on:
  push:
    branches:
      - docs
    tags: ["*"]
jobs:
  publish:
    name: publish 
    if: github.event_name == 'push' && github.ref == 'refs/heads/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - name: Publish documentation web page
        run: |
          ./.github/scripts/create-web-site.sh
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
